server:
    port: 80
spring:
    datasource:
        url: jdbc:mysql://192.168.29.131/zheye?useSSL=false&useUnicode=true
        username: root
        password: lwc950518
        driver-class-name: com.mysql.jdbc.Driver
mybatis:
    configuration:
        cache-enabled: true
        default-statement-timeout: 3000
        map-underscore-to-camel-case: true
        use-generated-keys: true
logging:
    level: debug