server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://192.168.29.131/zheye?useSSL=false&useUnicode=true
    username: root
    password: lwc950518
    driver-class-name: com.mysql.cj.jdbc.Driver
  freemarker:
    suffix: .html
  mvc:
    static-path-pattern: /**
mybatis:
  configuration:
    cache-enabled: true
    default-statement-timeout: 3000
    map-underscore-to-camel-case: true
    use-generated-keys: true
  mapper-locations: classpath:mybatis/mapper/*.xml
logging:
  level:
    com.liewmanchoi.zheye: debug